package com.darien.repositories_data.util

import com.darien.repositories_data.model.GithubReposResponseModel
import com.darien.repositories_data.model.Item
import com.darien.repositories_data.model.Owner

object ServerResponses {
    const val SUCCESS = """
        {
    "total_count": 2423,
    "incomplete_results": false,
    "items": [
        {
            "id": 24953448,
            "node_id": "MDEwOlJlcG9zaXRvcnkyNDk1MzQ0OA==",
            "name": "material-design-icons",
            "full_name": "google/material-design-icons",
            "private": false,
            "owner": {
                "login": "google",
                "id": 1342004,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzNDIwMDQ=",
                "avatar_url": "https://avatars.githubusercontent.com/u/1342004?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/google",
                "html_url": "https://github.com/google",
                "followers_url": "https://api.github.com/users/google/followers",
                "following_url": "https://api.github.com/users/google/following{/other_user}",
                "gists_url": "https://api.github.com/users/google/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/google/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/google/subscriptions",
                "organizations_url": "https://api.github.com/users/google/orgs",
                "repos_url": "https://api.github.com/users/google/repos",
                "events_url": "https://api.github.com/users/google/events{/privacy}",
                "received_events_url": "https://api.github.com/users/google/received_events",
                "type": "Organization",
                "site_admin": false
            },
            "html_url": "https://github.com/google/material-design-icons",
            "description": "Material Design icons by Google",
            "fork": false,
            "url": "https://api.github.com/repos/google/material-design-icons",
            "forks_url": "https://api.github.com/repos/google/material-design-icons/forks",
            "keys_url": "https://api.github.com/repos/google/material-design-icons/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/google/material-design-icons/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/google/material-design-icons/teams",
            "hooks_url": "https://api.github.com/repos/google/material-design-icons/hooks",
            "issue_events_url": "https://api.github.com/repos/google/material-design-icons/issues/events{/number}",
            "events_url": "https://api.github.com/repos/google/material-design-icons/events",
            "assignees_url": "https://api.github.com/repos/google/material-design-icons/assignees{/user}",
            "branches_url": "https://api.github.com/repos/google/material-design-icons/branches{/branch}",
            "tags_url": "https://api.github.com/repos/google/material-design-icons/tags",
            "blobs_url": "https://api.github.com/repos/google/material-design-icons/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/google/material-design-icons/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/google/material-design-icons/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/google/material-design-icons/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/google/material-design-icons/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/google/material-design-icons/languages",
            "stargazers_url": "https://api.github.com/repos/google/material-design-icons/stargazers",
            "contributors_url": "https://api.github.com/repos/google/material-design-icons/contributors",
            "subscribers_url": "https://api.github.com/repos/google/material-design-icons/subscribers",
            "subscription_url": "https://api.github.com/repos/google/material-design-icons/subscription",
            "commits_url": "https://api.github.com/repos/google/material-design-icons/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/google/material-design-icons/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/google/material-design-icons/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/google/material-design-icons/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/google/material-design-icons/contents/{+path}",
            "compare_url": "https://api.github.com/repos/google/material-design-icons/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/google/material-design-icons/merges",
            "archive_url": "https://api.github.com/repos/google/material-design-icons/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/google/material-design-icons/downloads",
            "issues_url": "https://api.github.com/repos/google/material-design-icons/issues{/number}",
            "pulls_url": "https://api.github.com/repos/google/material-design-icons/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/google/material-design-icons/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/google/material-design-icons/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/google/material-design-icons/labels{/name}",
            "releases_url": "https://api.github.com/repos/google/material-design-icons/releases{/id}",
            "deployments_url": "https://api.github.com/repos/google/material-design-icons/deployments",
            "created_at": "2014-10-08T18:01:28Z",
            "updated_at": "2023-04-09T22:04:05Z",
            "pushed_at": "2023-03-23T03:54:32Z",
            "git_url": "git://github.com/google/material-design-icons.git",
            "ssh_url": "git@github.com:google/material-design-icons.git",
            "clone_url": "https://github.com/google/material-design-icons.git",
            "svn_url": "https://github.com/google/material-design-icons",
            "homepage": "http://google.github.io/material-design-icons/",
            "size": 1778238,
            "stargazers_count": 47861,
            "watchers_count": 47861,
            "language": null,
            "has_issues": true,
            "has_projects": true,
            "has_downloads": false,
            "has_wiki": false,
            "has_pages": true,
            "has_discussions": false,
            "forks_count": 9585,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 206,
            "license": {
                "key": "apache-2.0",
                "name": "Apache License 2.0",
                "spdx_id": "Apache-2.0",
                "url": "https://api.github.com/licenses/apache-2.0",
                "node_id": "MDc6TGljZW5zZTI="
            },
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [
                "android",
                "icons",
                "ios",
                "material",
                "material-design",
                "sprites",
                "web"
            ],
            "visibility": "public",
            "forks": 9585,
            "open_issues": 206,
            "watchers": 47861,
            "default_branch": "master",
            "score": 1.0
        },
        {
            "id": 20300177,
            "node_id": "MDEwOlJlcG9zaXRvcnkyMDMwMDE3Nw==",
            "name": "guava",
            "full_name": "google/guava",
            "private": false,
            "owner": {
                "login": "google",
                "id": 1342004,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzNDIwMDQ=",
                "avatar_url": "https://avatars.githubusercontent.com/u/1342004?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/google",
                "html_url": "https://github.com/google",
                "followers_url": "https://api.github.com/users/google/followers",
                "following_url": "https://api.github.com/users/google/following{/other_user}",
                "gists_url": "https://api.github.com/users/google/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/google/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/google/subscriptions",
                "organizations_url": "https://api.github.com/users/google/orgs",
                "repos_url": "https://api.github.com/users/google/repos",
                "events_url": "https://api.github.com/users/google/events{/privacy}",
                "received_events_url": "https://api.github.com/users/google/received_events",
                "type": "Organization",
                "site_admin": false
            },
            "html_url": "https://github.com/google/guava",
            "description": "Google core libraries for Java",
            "fork": false,
            "url": "https://api.github.com/repos/google/guava",
            "forks_url": "https://api.github.com/repos/google/guava/forks",
            "keys_url": "https://api.github.com/repos/google/guava/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/google/guava/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/google/guava/teams",
            "hooks_url": "https://api.github.com/repos/google/guava/hooks",
            "issue_events_url": "https://api.github.com/repos/google/guava/issues/events{/number}",
            "events_url": "https://api.github.com/repos/google/guava/events",
            "assignees_url": "https://api.github.com/repos/google/guava/assignees{/user}",
            "branches_url": "https://api.github.com/repos/google/guava/branches{/branch}",
            "tags_url": "https://api.github.com/repos/google/guava/tags",
            "blobs_url": "https://api.github.com/repos/google/guava/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/google/guava/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/google/guava/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/google/guava/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/google/guava/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/google/guava/languages",
            "stargazers_url": "https://api.github.com/repos/google/guava/stargazers",
            "contributors_url": "https://api.github.com/repos/google/guava/contributors",
            "subscribers_url": "https://api.github.com/repos/google/guava/subscribers",
            "subscription_url": "https://api.github.com/repos/google/guava/subscription",
            "commits_url": "https://api.github.com/repos/google/guava/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/google/guava/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/google/guava/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/google/guava/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/google/guava/contents/{+path}",
            "compare_url": "https://api.github.com/repos/google/guava/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/google/guava/merges",
            "archive_url": "https://api.github.com/repos/google/guava/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/google/guava/downloads",
            "issues_url": "https://api.github.com/repos/google/guava/issues{/number}",
            "pulls_url": "https://api.github.com/repos/google/guava/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/google/guava/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/google/guava/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/google/guava/labels{/name}",
            "releases_url": "https://api.github.com/repos/google/guava/releases{/id}",
            "deployments_url": "https://api.github.com/repos/google/guava/deployments",
            "created_at": "2014-05-29T16:23:17Z",
            "updated_at": "2023-04-09T20:36:30Z",
            "pushed_at": "2023-04-07T21:50:41Z",
            "git_url": "git://github.com/google/guava.git",
            "ssh_url": "git@github.com:google/guava.git",
            "clone_url": "https://github.com/google/guava.git",
            "svn_url": "https://github.com/google/guava",
            "homepage": "",
            "size": 413166,
            "stargazers_count": 47176,
            "watchers_count": 47176,
            "language": "Java",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": true,
            "has_discussions": false,
            "forks_count": 10475,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 768,
            "license": {
                "key": "apache-2.0",
                "name": "Apache License 2.0",
                "spdx_id": "Apache-2.0",
                "url": "https://api.github.com/licenses/apache-2.0",
                "node_id": "MDc6TGljZW5zZTI="
            },
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [
                "guava",
                "java"
            ],
            "visibility": "public",
            "forks": 10475,
            "open_issues": 768,
            "watchers": 47176,
            "default_branch": "master",
            "score": 1.0
        },
        {
            "id": 364474335,
            "node_id": "MDEwOlJlcG9zaXRvcnkzNjQ0NzQzMzU=",
            "name": "zx",
            "full_name": "google/zx",
            "private": false,
            "owner": {
                "login": "google",
                "id": 1342004,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzNDIwMDQ=",
                "avatar_url": "https://avatars.githubusercontent.com/u/1342004?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/google",
                "html_url": "https://github.com/google",
                "followers_url": "https://api.github.com/users/google/followers",
                "following_url": "https://api.github.com/users/google/following{/other_user}",
                "gists_url": "https://api.github.com/users/google/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/google/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/google/subscriptions",
                "organizations_url": "https://api.github.com/users/google/orgs",
                "repos_url": "https://api.github.com/users/google/repos",
                "events_url": "https://api.github.com/users/google/events{/privacy}",
                "received_events_url": "https://api.github.com/users/google/received_events",
                "type": "Organization",
                "site_admin": false
            },
            "html_url": "https://github.com/google/zx",
            "description": "A tool for writing better scripts",
            "fork": false,
            "url": "https://api.github.com/repos/google/zx",
            "forks_url": "https://api.github.com/repos/google/zx/forks",
            "keys_url": "https://api.github.com/repos/google/zx/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/google/zx/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/google/zx/teams",
            "hooks_url": "https://api.github.com/repos/google/zx/hooks",
            "issue_events_url": "https://api.github.com/repos/google/zx/issues/events{/number}",
            "events_url": "https://api.github.com/repos/google/zx/events",
            "assignees_url": "https://api.github.com/repos/google/zx/assignees{/user}",
            "branches_url": "https://api.github.com/repos/google/zx/branches{/branch}",
            "tags_url": "https://api.github.com/repos/google/zx/tags",
            "blobs_url": "https://api.github.com/repos/google/zx/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/google/zx/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/google/zx/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/google/zx/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/google/zx/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/google/zx/languages",
            "stargazers_url": "https://api.github.com/repos/google/zx/stargazers",
            "contributors_url": "https://api.github.com/repos/google/zx/contributors",
            "subscribers_url": "https://api.github.com/repos/google/zx/subscribers",
            "subscription_url": "https://api.github.com/repos/google/zx/subscription",
            "commits_url": "https://api.github.com/repos/google/zx/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/google/zx/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/google/zx/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/google/zx/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/google/zx/contents/{+path}",
            "compare_url": "https://api.github.com/repos/google/zx/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/google/zx/merges",
            "archive_url": "https://api.github.com/repos/google/zx/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/google/zx/downloads",
            "issues_url": "https://api.github.com/repos/google/zx/issues{/number}",
            "pulls_url": "https://api.github.com/repos/google/zx/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/google/zx/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/google/zx/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/google/zx/labels{/name}",
            "releases_url": "https://api.github.com/repos/google/zx/releases{/id}",
            "deployments_url": "https://api.github.com/repos/google/zx/deployments",
            "created_at": "2021-05-05T05:50:01Z",
            "updated_at": "2023-04-09T21:07:48Z",
            "pushed_at": "2023-04-06T12:23:22Z",
            "git_url": "git://github.com/google/zx.git",
            "ssh_url": "git@github.com:google/zx.git",
            "clone_url": "https://github.com/google/zx.git",
            "svn_url": "https://github.com/google/zx",
            "homepage": "https://npmjs.com/package/zx",
            "size": 501,
            "stargazers_count": 36954,
            "watchers_count": 36954,
            "language": "JavaScript",
            "has_issues": true,
            "has_projects": false,
            "has_downloads": true,
            "has_wiki": false,
            "has_pages": true,
            "has_discussions": true,
            "forks_count": 887,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 35,
            "license": {
                "key": "apache-2.0",
                "name": "Apache License 2.0",
                "spdx_id": "Apache-2.0",
                "url": "https://api.github.com/licenses/apache-2.0",
                "node_id": "MDc6TGljZW5zZTI="
            },
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [
                "bash",
                "cli",
                "javascript",
                "nodejs",
                "shell"
            ],
            "visibility": "public",
            "forks": 887,
            "open_issues": 35,
            "watchers": 36954,
            "default_branch": "main",
            "score": 1.0
        }
    ]
}
    """

    const val ERROR = """
        {
    "message": "Validation Failed",
    "errors": [
        {
            "message": "The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.",
            "resource": "Search",
            "field": "q",
            "code": "invalid"
        }
    ],
    "documentation_url": "https://docs.github.com/v3/search/"
}
    """
}

fun generateFakeResponseModel(): GithubReposResponseModel {
    val items = mutableListOf<Item>()
    items.add(
        Item(
            description = "Material Design icons by Google",
            html_url = "https://github.com/google/material-design-icons",
            language = null,
            id = 24953448,
            owner = Owner(
                avatar_url = "https://avatars.githubusercontent.com/u/1342004?v=4",
                login = "google"
            ),
            name = "material-design-icons",
            stargazers_count = 47861,
            updated_at = "2023-04-09T22:04:05Z"
        )
    )
    return GithubReposResponseModel(incomplete_results = false, items = items, total_count = 2423)
}